# Generated by Django 5.1 on 2025-01-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=150)),
                ('sub_category', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=110)),
                ('price', models.IntegerField(default=0)),
                ('images', models.CharField(max_length=150)),
                ('product_details', models.CharField(max_length=500)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=5)),
                ('out_of_stock', models.BooleanField(default=False)),
                ('seller', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
