# Generated by Django 5.1 on 2025-01-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
