# Generated by Django 5.1 on 2025-01-26 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ordered',
        ),
    ]
