# Generated by Django 5.1 on 2025-01-12 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='default_address',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.addressbook'),
        ),
    ]
