# Generated by Django 5.1 on 2025-01-24 09:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_memo_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
