# Generated by Django 5.1 on 2025-01-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_coupon_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
