# Generated by Django 5.1 on 2025-01-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_memo_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='total',
        ),
    ]
