# Generated by Django 5.1 on 2025-01-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_orderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
