# Generated by Django 5.1 on 2025-01-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_orderhistory_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='MedalType',
            field=models.CharField(default='Gold', max_length=50),
        ),
    ]
