# Generated by Django 5.1 on 2025-01-31 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_cart_medaltype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='MedalType',
        ),
    ]
